YunoHost/ynh-dev

ynh-dev
As some of us experienced a few times, running "ynh-dev use" several times actually creates symlinks inside symlinks, (e.g. a "yunohost" symlink *inside* `yunohost/src/yunohost/`), which leads to moulinette taking a great deal of time running command because it tries to do infinite includes somehow...
This is due to missing option `-n` for `ln` (see [this article](http://blog.endpoint.com/2009/09/using-ln-sf-to-replace-symlink-to.html))
=> [fix] Avoid symlinkception when running 'ynh-dev use' several times

ynh-dev
Simplify the code using a generic function for symlink creation.
I tested for SSOwat, yunohost and moulinette packages and it works perfectly.
=> [enh] use generic function for symlink creation.

ynh-dev
It allow you to run several unstable instances by running 2 run command with different domains:
./ynh-dev run domain1.local unstable
./ynh-dev run domain2.local unstable
In my case I used it to keep my special VPN yunohost instance and be able to test your pull request with an other environment. An other way was to create several env with create-env command...
=> [enh] Be able to run multiple vagrant instances

ynh-dev
Unit tests are live but are not well-documented so far.
I suggest adding a 'test' action in ./ynh-dev, so that you just have to run something like `./ynh-dev test yunohost` to automatically setup the test dependencies (including the test apps) and run the tests.
=> [enh] "./ynh-dev test" to deploy, update and run unit test stuff

ynh-dev
Allow to run several VM with the same box origin.
IMPORTANT: this fix break some retro compatibility:
If before you have done
`ynh-dev run toto.local unstable`
With this script you can't get back to the vm with the same command, but you can do this with:
`ynh-dev run unstable unstable`
Use case: 
Be able to test openvpn_ynh with vpnclient_ynh (2 vm needed).
Be able to code on "federated" yunohost (friend backup ...)
Test the good creation of vm (creation, update, postinstall)
Be able to keep a vm with change (app packaging process... try first, write in the install script next...)
https://dev.yunohost.org/issues/931
=> [fix] Cant create multiple vm (Redmine 931)

ynh-dev
A small dependency is missing. Without it the yunohost backup tests fail.
Just add the mock dependency
Work finished
Micro decision, I mark it as ready to merge
=> [fix] Missing dependency: mock

ynh-dev
The suggested command launch sh without executing the command
Using `bash -c` instead.
=> Suggested command doesn't work

ynh-dev
I tried to move directly in `/vagrant` folder but it doesn't works with:
```bash
vagrant ssh $VMNAME -c "sudo -i; cd /vagrant"
```
=> [enh] use 'root' user after ssh authentication

ynh-dev
Hey there,
I managed to create an unstable stretch box with Yunohost pre-installed (from branch stretch). This should make things much easier to test and develop on stretch. 
This was built with some pretty dirty recipes from https://github.com/YunoHost/Vagrantfile/tree/stretch/prebuild and https://github.com/YunoHost/install_script/tree/stretch . These should get cleaner as we start putting the right infrastructure in place (e.g. building proper debian packages).
On this image, at this point you should be able to postinstall and perform basic operations on users and domains. Apps not tested yet. See the todo [on this pad](https://pad.aposti.net/p/ynh-stretch). I haven't really tested `ynh-dev use-git` for now, but this should be fine as long as your branch is based on the `stretch` …
=> [enh] Add unstable stretch box

ynh-dev
Fix several issues encountered when running `./ynh-dev run ynhdev.local stable` on macOS.
* Unlike GNU-sed, BSD-sed `-i` option requires an explicit backup
extension.
* Newlines are difficult to get right on different versions of `sed`.
This commit replaces the `sed` invocation with `perl`. It does the same job with almost the same syntax, but avoids portability issues.
`\s` for matching spaces is a GNU-sed extension. The portable way is to use `[[:space]]` instead.
=> Fix macOS/BSD portability

ynh-dev
It's been 7 months now, so that's probably not relevant anymore and might generate confusion for new users of this tool 😉
=> Remove old warning about previous behavior

ynh-dev
Stable and testing images no longer exist on build.yunohost.org. This PR removes them from the script.
=> [fix] Remove stable and testing because images do not exist anymore

ynh-dev
- `global.py` wasn't symlinked:
```bash
yunohost --version
Traceback (most recent call last):
File "/usr/bin/yunohost", line 34, in <module>
import moulinette
File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 3, in <module>
from moulinette.core import init_interface, MoulinetteError, MoulinetteSignals, Moulinette18n
File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 13, in <module>
from moulinette.globals import LOCALES_DIR, LIB_DIR
ImportError: No module named globals
```
Best solution is to symlink the whole folder. Simpler symlink plz!!
=> [fix] use global symlink for 'moulinette'.

ynh-dev
The place where locales are put is /usr/share/moulinette/locale and not locales !
=> [fix] locales moulinette go into locale folder

ynh-dev
Debian is doing debian things again so now npm is not present in stretch for whatever reason that I don't want to know.
This code handles running `./ynh-dev use-git yunohost-admin` on both stretch and jessie.
Testing and working for me.
=> [fix] support stretch for npm/gulp

.gitignore
I've added the line ".vagrant" in the gitignore because vagrant create this file which is not included in the repo, when we follow the "how to contribute" documentation.
=> Add .vagrant in gitignore

README.md
I've fixed (what I think is) a typo in the REAME.md. 
Line 132: "PACKAGE should can be ssowat […]"
(Sorry for these micro PR :x)
=> [doc] fix a minor typo in the README

README.md
Closes https://github.com/YunoHost/issues/issues/1352.
Someone with permissions would have to edit the repository description to change that link as well. Please see https://github.com/YunoHost/issues/issues/1352#issue-445832752 for mroe on that.
=> Point to default language page.

ynh-dev
When there are symlinks in directories contained by current path then lxc fails with :
Error: Invalid devices: Device validation failed "ynhdev-shared-folder": Missing source "(...)/ynh-dev" for disk "ynhdev-shared-folder"
using readlink -f to obtain full path.
=> support symlinks within ynh-dev path

README.md
on debian buster at least. Avoir enigmatic message : 
See https://forum.snapcraft.io/t/snap-lxd-assumes-unsupported-features-snapd2-39/17542/6
=> Add missing step installing lxd

ynh-dev
For now it's not an overwrite of the current command to run yunohost-admin dev environment, it's another command => `./ynh-dev use-git yunohost-admin-vue` with another clone.  
The command adds the port `8080` in the firewall opened ports because we use webpack-dev-server. This allows hot-reloads and bunch of features (there is no need to fully rebuild the js at each file modification).
The command also creates a `.env` file with the lxc IP so the webpack-dev-server can proxy API requests.  
??
You need to add another repo in `ynh-dev/` so we can switch between old/new versions.
```bash
git clone -b enh-vuejs --single-branch https://github.com/Axolotle/yunohost-admin yunohost-admin-vue
./ynh-dev use-git yunohost-admin-vue
```
=> Port to Vue.js (dev setup)

README.md, ynh-dev
- Add the yunohost remote to speed up deployment
- Add the possibility to choose the yunohost version (stable, testing, unstable)
We must build lxc images in devbaseimgs.yunohost.org
=> use yunohost lxd remote + add the possibility to choose the yunohost version

ynh-dev
The /bin/bash path is not POSIX and it can cause issues.
This PR fixes two issues I had using it on NixOS.
=> Fix POSIX ynh-dev script's compability

README.md
One commit per line, you don't have to pick both if you want.
=> Update README to warn (again) about port 53 and to tell to use "yunohost postinstall"

deploy.sh, ynh-dev
- Set bookworm as default dist
- Add `./ynh-dev yunohost-portal` to run dev server inside container (same as webadmin)
- Add `./ynh-dev yunohost-portal-build` to simply build the app and override default sources (no need to open ports, setup `.env`, `etc/hosts` and `/etc/yunohost/.portal-api-allowed-cors-origins`)
=> enh: Bookworm + new portal

README.md
The current Incus installation works only for Debian 13 or Ubuntu 24.04.
The documentation is updated to take into account that some people have older distros
=> Update Incus installation for older distros

ynh-dev
- use command instead of which (archlinux doesn't have which installed by default, command is POSIX compliant)
- root user doesn't need to be in `incus-admin` group
- jq is also a dependency
=> More portable dependency checks

ynh-dev
As discussed (here)[https://github.com/YunoHost/issues/issues/2463], the DNS name resolution is not working inside the LXC container. This is due to a missing DHCP client so the upstream DNS server is never configured.
Running `dhclient` after startup fixes this issue.
I'm however not sure if this is the most elegant solution.
Fixes https://github.com/YunoHost/issues/issues/2463
=> Run dhcp client after startup
